name: OHW20
channels:
  - conda-forge
dependencies:
  - python=3.8
  - argopy
  - bokeh
  - cartopy
  - cdsapi
  - cf-units
  - colorcet
  - datashader
  - erddapy
  - geolinks
  - geopandas
  - geoviews
  - gsw
  - holoviews
  - hvplot
  - ioos-tools
  - ioos_qc
  - ipyleaflet
  - jupyter
  - jupyter-rsession-proxy
  - jupyter_contrib_nbextensions
  - matplotlib-base
  - nc-time-axis
  - netcdf4
  - numpy
  - palettable
  - pandas
  - panel
  - param
  - podaacpy
  - pyoos
  - rasterio
  - requests
  - retrying
  - seaborn
  - shapely
  - siphon
  - xarray
  - xlrd
  # R packages
  - r-base
  # - r-phyloseq (not in cran)
  - r-ape
  - r-cowplot
  - r-crul
  # - r-dplyr  installs with tidyverse
  # - r-ggplot2 installs with tidyverse
  - r-gridextra
  - r-gsw
  - r-irkernel
  - r-leaflet
  # - r-magrittr installs with tidyverse
  - r-mapdata
  - r-maps
  - r-maptools
  - r-ncdf4
  - r-oce
  - r-patchwork
  - r-plotly
  - r-remotes
  - r-raster
  - r-rastervis
  # - r-rcolorbrewer installs with ggplot2
  # - r-readr installs with tidyverse
  # - r-scales installs with ggplot2
  -r-rgdal
  -r-rgeos
  - r-sf
  - r-tidyverse
  - r-vegan
  - rpy2
  # extras
  - conda-lock
  - emacs
  - git
  - graphviz
  - unzip
  - vim
  - zip
