name: OHW20
channels:
  - conda-forge
dependencies:
  - python=3.8
  - argopy
  - bokeh
  - cartopy
  - colorcet
  - datashader
  - erddapy
  - geopandas
  - geoviews
  - gsw
  - holoviews
  - hvplot
  - ipyleaflet
  - jupyter
  - jupyter-rsession-proxy
  - jupyter_contrib_nbextensions
  - matplotlib-base
  - netcdf4
  - numpy
  - palettable
  - pandas
  - panel
  - param
  - podaacpy
  - pyoos
  - rasterio
  - requests
  - retrying
  - rise
  - seaborn
  - shapely
  - siphon
  - xarray
  - xlrd
  # R packages
  - r-base
  - r-irkernel
  - r-tidyverse
  - rpy2
  - r-gsw
  - r-oce
  # extras
  - vim
  - emacs
  - git
  - graphviz
  - zip
  - unzip
  - conda-lock
  
